import { Oxanium } from 'next/font/google';
import './globals.css';
import { EventProvider } from '@/context/EventProvider';

const oxanium = Oxanium({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oxanium.className}>
        <EventProvider>{children}</EventProvider>
      </body>
    </html>
  );
}
